"""
WHY:
The ContactResponse schema defines the exact structure of data returned by the
ContactBook API whenever a contact is retrieved, created, or updated. While the
ContactCreate and ContactUpdate schemas validate incoming data, ContactResponse
ensures that outgoing data is consistent, complete, and predictable. This schema
acts as the public-facing representation of a contact record, making it easier
for clients, developers, and documentation tools (like Swagger UI) to understand
what the API returns.

DESIGN:
1. The id field uniquely identifies each contact. It is generated by the API and
   included in every response so clients can reference, update, or retrieve the
   contact later.

2. first_name, last_name, email, phone, and contact_type mirror the fields from
   ContactCreate and ContactUpdate. Returning these fields ensures that clients
   always receive the full, current state of a contact after any operation.

3. contact_type uses the ContactType Enum, guaranteeing that the response always
   contains one of the valid, predefined types (personal or business). This keeps
   the API consistent and makes filtering by contact_type reliable.

4. created_at records when the contact was first added to the system. Including
   this timestamp helps clients track when a contact was created and supports
   auditability.

5. updated_at records the most recent modification time. This is not required by
   the assignment but is a valuable enhancement. It allows clients to detect
   changes, synchronize data, and maintain accurate records.

6. All fields use Pydantic's Field() metadata to provide examples in Swagger UI.
   This improves API usability by showing developers exactly what valid response
   data looks like.

Overall, the ContactResponse schema provides a clean, structured, and complete
representation of a contact record. It ensures that every API response is
consistent, strongly typed, and easy to consume.
"""




from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from app.schemas.contact_create import ContactType

class ContactResponse(BaseModel):
    id: int = Field(..., example=1)
    first_name: str = Field(..., min_length=1, max_length=50, example="John")
    last_name: str = Field(..., min_length=1, max_length=50, example="Doe")
    email: str = Field(..., example="john.doe@example.com")
    phone: Optional[str] = Field(None, min_length=10, max_length=15, example="5551234567")
    contact_type: ContactType = Field(..., example="personal")
    created_at: datetime = Field(..., example="2023-01-01T00:00:00")
    updated_at: datetime = Field(..., example="2023-01-01T00:00:00")